### ISSUE TITLE
Add info to provenance

### ISSUE THREAD

**Issue by laurentsimon** [gossts/slsa-go#10]
Look at info in https://slsa.dev/provenance/v0.2 for additions.

For example, `buildConfig` looks like the build command? Need to find a place to list env variables too

**Comment by asraa** [comment]
Currently `invocation.environment` contains the env vars, which we should add a full list to:
```
{
  "_type": "https://in-toto.io/Statement/v0.1",
  "predicateType": "https://slsa.dev/provenance/v0.2",
  "subject": [
    {
      "name": "binary-linux-amd64",
      "digest": {
        "sha256": "0ae7e4fa71686538440012ee36a2634dbaa19df2dd16a466f52411fb348bbc4e"
      }
    }
  ],
  "predicate": {
    "builder": {
      "id": "https://github.com/Attestations/GitHubHostedActions@v1"
    },
    "buildType": "https://github.com/Attestations/GitHubActionsWorkflow@v1",
    "invocation": {
      "configSource": {
        "uri": "git+asraa/slsa-on-github-test.git",
        "digest": {
          "SHA1": "0dfcd24824432c4ce587f79c918eef8fc2c44d7b"
        },
        "entryPoint": "Test SLSA"
      },
      "environment": {
        "arch": "amd64",
        "env": {
          "GITHUB_EVENT_NAME": "workflow_dispatch",
          "GITHUB_RUN_ID": "1924173960",
          "GITHUB_RUN_NUMBER": "89"
        }
      }
    },
    "materials": [
      {
        "uri": "git+asraa/slsa-on-github-test.git",
        "digest": {
          "SHA1": "0dfcd24824432c4ce587f79c918eef8fc2c44d7b"
        }
      }
    ]
  }
}
```

**Comment by laurentsimon** [comment]
Gotcha! I can export these from the builder. Assigning to me.

**Comment by laurentsimon** [comment]
quick questions:
- `"entryPoint": "<STRING>"` -> should this be the name/path of the workflow? The slsa.dev website says `his is often a path to a configuration file and/or a target label within that file`
- `builder.id` and `buildType` -> should this be more specific and say `github.com/gossts/slsa-go/github/workflow/build.yml@<hash>`? Maybe something we should propose to SLSA community. The generic `https://github.com/Attestations/GitHubActionsWorkflow@v1` does not differentiate between actions. Just a thought
- `invocation.parameters` -> do we need to add the trigger name?

I'm going to start with `buildConfig`. It's not entirely clear to me whether the env should be part of the builder or arguments within `buildConfig`

**Comment by asraa** [comment]
> should this be the name/path of the workflow?

I think given that this should be path to the workflow and then the target label... may be the name of the job executing the build (reuseable workflow job?)

> The generic https://github.com/Attestations/GitHubActionsWorkflow@v1 does not differentiate between actions. Just a thought

Builder ID does make sense to pin to the reuseable workflow, but somehow the information that this is a github hosted builder should be clear. Maybe this is the type? self hosted or github hosted?

> invocation.parameters -> do we need to add the trigger name?

Yes I think so! Since it is a user controlled input to the invocation.

**Comment by laurentsimon** [comment]
cc @[tomhennen](https://github.com/tomhennen) any advice on the above?

**Comment by laurentsimon** [comment]
> > should this be the name/path of the workflow?
> 
> I think given that this should be path to the workflow and then the target label... may be the name of the job executing the build (reuseable workflow job?)

I'm not sure. I was thinking this should be the calling workflow instead, since it's under `ConfigSource` which seems to refer to the source repo we're compiling.  Asked in https://github.com/in-toto/in-toto-golang/issues/159

> > The generic https://github.com/Attestations/GitHubActionsWorkflow@v1 does not differentiate between actions. Just a thought
> 
> Builder ID does make sense to pin to the reuseable workflow, but somehow the information that this is a github hosted builder should be clear. Maybe this is the type? self hosted or github hosted?

sg.

> > invocation.parameters -> do we need to add the trigger name?
> 
> Yes I think so! Since it is a user controlled input to the invocation.

sg

**Comment by laurentsimon** [comment]
use conclusion of https://github.com/gossts/slsa-provenance/issues/11#issuecomment-1059603473 once it's resolved

**Comment by laurentsimon** [comment]
fyi, request to add more fields to the buildConfig https://github.com/in-toto/in-toto-golang/issues/159

**Comment by laurentsimon** [comment]
We should investigate capturing runner OS's information if available in `/etc`

**Comment by laurentsimon** [comment]
follow this thread https://github.com/slsa-framework/slsa/issues/319

**Comment by laurentsimon** [comment]
> > > should this be the name/path of the workflow?
> > 
> > 
> > I think given that this should be path to the workflow and then the target label... may be the name of the job executing the build (reuseable workflow job?)

@MarkLodato could you confirm? I'm confused whether this should be the reusable workflow (already mentioned in the buildConfig) or the calling workflow

**Comment by laurentsimon** [comment]
sadly `"entryPoint": "<STRING>"` is populated with the workflow name by default https://docs.github.com/en/actions/learn-github-actions/contexts, and I suspect the one in the token is the same https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#understanding-the-oidc-token... (I'll double check)

The `job_workflow_ref` is accessible in the OIDC JWT, but not in the GitHub event info AFAICT, so we'll query for a JWT token ourselves (see  https://github.com/sigstore/cosign/blob/739947de3d0197fbaab926bd9b896963ebf47a19/pkg/providers/github/github.go)

`value` is base64url-encoded (`X.Y.Z`), then just parse the JWT token

**Comment by MarkLodato** [comment]
Here is what I recommend:

`builder.id`: Identifies the reusable workflow and must match the value from the OIDC token.

* Value: `"https://github.com/"` + `job_workflow_ref`
* Example: `"https://github.com/gossts/slsa-go/.github/workflows/build.yml@<ref>"`
* TODO: Make sure this works with non-github.com domains for GitHub Enterprise.


`buildType`: Identifies how to interpret this build, i.e. that this is a slsa-go build and not something else. It's not just a "github actions" because this is specifically a go build.

* Value: `"https://gosts.github.io/slsa-go/v1"` (or something like that)

`invocation.configSource`: Identifies the top-level input to the reusable workflow, i.e. the caller's workflow. You don't need to use the OIDC token here. Instead, grab it from the [`github` context](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context) ([example](https://github.com/MarkLodato/example-build/runs/5543573873?check_suite_focus=true#step:2:301)).

* Value:

  ```jsonc
  {
    "uri": "git+${{github.server_url}}/${{github.repo}}@${{github.ref_name}}",
    "digest": { "sha1": "${{github.sha}}" },
    "entryPoint": "${{github.workflow}}"
  }
  ```

* Example:

  ```jsonc
  {
    "uri": "git+https://github.com/MarkLodato/example-build@main",
    "digest": { "sha1": "3c850d2421783d7adb364c189436ceeb57ead181" },
    "entryPoint": ".github/workflows/build.yaml"
  }
  ```

`invocation.parameters`: Parameters coming from the trigger event.

* Value: `${{github.event.inputs}}`

`invocation.environment`: Non-user-controllable things needed to reproduce the build. OK to omit for now.

**Comment by laurentsimon** [comment]
Thanks Mark!

I think we should also add some of the GitHub context information to the `invocation.parameters`, because certain events like `schedule` don't have an event's payload. We still want to know which branch/ref the `schedule` was for, for example. (Note: current schedule events are always for the default branch, but this may change in the future)

**Comment by Dreamypops33** [comment]
Sorry for not responding to your text and emails. My family was I'll my dad has had several strokes and suffers from dementia. So i have not been as loyal them the COVID had a very strong impact on myself ending up homeless, barely able to eat considering i have a child. I was taking care of such a wonderful role model dad, a overworked retired mom and almost lost all time to focus on this wonderful development. Perhaps it's not to late to continue this great development. JASON HOWARD IS MY NE.. EMAIL ME jhowardstop@outlook.com OR JUST CALL 5014955893.  PLEASE DONT BE Shy.
